#define EMF_TEXT_BLACK		"\x1b[30m"
#define EMF_TEXT_RED		"\x1b[31m"
#define EMF_TEXT_GREEN		"\x1b[32m"
#define EMF_TEXT_YELLOW		"\x1b[33m"
#define EMF_TEXT_BLUE		"\x1b[34m"
#define EMF_TEXT_MAGENTA	"\x1b[35m"
#define EMF_TEXT_CYAN		"\x1b[36m"
#define EMF_TEXT_WHITE		"\x1b[37m"

#define EMF_TEXT_NORMAL		"\x1b[0m"
#define EMF_TEXT_BOLD		"\x1b[1m"
#define EMF_TEXT_UNDERSCORE	"\x1b[4m"
